main:
  method: 'get'
  path: ~
  controller: App\Controller\HomeController
  action: index


details:
  method: 'get'
  path: 'show/{id}'
  controller: App\Controller\DetailsController
  action: details


